# Generated by Django 4.0.6 on 2022-09-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_alter_user_profile_image_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='imagen_perfil/'),
        ),
    ]
